// <auto-generated />
namespace PaganaSoft.ORM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ActulizarNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActulizarNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201309190332338_ActulizarNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
